import pandas as pd

from config.schema import MASTER_SCHEMA, EXTRACTION_FIELDS


class ExcelManager:
    """Manages the application's master schema and Excel exports."""

    def get_headers(self):
        """Return the complete master schema."""
        return MASTER_SCHEMA.copy()

    def get_extraction_headers(self):
        """Return fields that should be extracted from documents."""
        return EXTRACTION_FIELDS.copy()

    def validate_record(self, record):
        """Validate a record against the extraction schema."""

        if not isinstance(record, dict):
            raise TypeError("Record must be a dictionary.")

        allowed_fields = set(EXTRACTION_FIELDS)
        actual_fields = set(record.keys())

        extra_fields = actual_fields - allowed_fields

        if extra_fields:
            raise ValueError(
                f"Unexpected fields found: {sorted(extra_fields)}"
            )

        return True

    def create_dataframe(self, records):
        """Create a dataframe using the exact master schema order."""

        rows = []

        for record in records:
            self.validate_record(record)

            row = {
                field: record.get(field)
                for field in EXTRACTION_FIELDS
            }

            rows.append(row)

        df = pd.DataFrame(rows, columns=EXTRACTION_FIELDS)

        # Sr. No. is generated by the application.
        df.insert(
            0,
            "Sr. No.",
            range(1, len(df) + 1)
        )

        return df
