from pathlib import Path
import pandas as pd


class ExcelManager:
    """Manages the master Excel schema and Excel exports."""

    DEFAULT_TEMPLATE_PATH = Path("config") / "master_template.xlsx"
    DEFAULT_SHEET_NAME = "Master Schema"

    def __init__(self, template_path=None):
        self.template_path = Path(
            template_path or self.DEFAULT_TEMPLATE_PATH
        )

        self.sheet_name = self.DEFAULT_SHEET_NAME
        self.headers = self._load_headers()

    def _load_headers(self):
        """Load and validate headers from the master Excel template."""

        if not self.template_path.exists():
            raise FileNotFoundError(
                f"Master Excel template not found: {self.template_path}"
            )

        try:
            df = pd.read_excel(
                self.template_path,
                sheet_name=self.sheet_name,
                header=0
            )
        except ValueError as exc:
            raise ValueError(
                f"Excel sheet '{self.sheet_name}' was not found "
                f"in {self.template_path}."
            ) from exc
        except Exception as exc:
            raise RuntimeError(
                f"Unable to read master Excel template: {exc}"
            ) from exc

        headers = [
            str(column).strip()
            for column in df.columns
            if str(column).strip()
        ]

        if not headers:
            raise ValueError(
                "Master Excel template does not contain any headers."
            )

        if len(headers) != len(set(headers)):
            raise ValueError(
                "Master Excel template contains duplicate headers."
            )

        return headers

    def get_headers(self):
        """Return the complete master schema in exact order."""
        return self.headers.copy()

    def get_extraction_headers(self):
        """Return fields that Gemini should extract."""
        return [
            header
            for header in self.headers
            if header != "Sr. No."
        ]

    def validate_record(self, record):
        """Validate that a record follows the master schema."""

        if not isinstance(record, dict):
            raise TypeError("Record must be a dictionary.")

        expected = set(self.get_extraction_headers())
        actual = set(record.keys())

        extra_fields = actual - expected

        if extra_fields:
            raise ValueError(
                f"Record contains unexpected fields: {sorted(extra_fields)}"
            )

        return True

    def create_dataframe(self, records):
        """Create a dataframe using the exact master schema order."""

        extraction_headers = self.get_extraction_headers()

        rows = []

        for record in records:
            self.validate_record(record)

            row = {
                header: record.get(header)
                for header in extraction_headers
            }

            rows.append(row)

        df = pd.DataFrame(rows, columns=extraction_headers)

        # Sr. No. is generated by the application.
        df.insert(
            0,
            "Sr. No.",
            range(1, len(df) + 1)
        )

        return df
