import pandas as pd

from config.schema import MASTER_SCHEMA, EXTRACTION_FIELDS


class ExcelManager:
    """Manages the application's master schema and Excel data preparation."""

    def get_headers(self):
        """Return a copy of the complete master schema."""
        return MASTER_SCHEMA.copy()

    def get_extraction_headers(self):
        """Return a copy of fields that should be extracted."""
        return EXTRACTION_FIELDS.copy()

    def validate_record(self, record):
        """
        Validate a single record against the extraction schema.

        The record must:
        - be a dictionary
        - contain exactly the expected extraction fields
        - not contain generated fields such as Sr. No.
        """

        if not isinstance(record, dict):
            raise TypeError(
                "Credential record must be a dictionary."
            )

        expected_fields = set(EXTRACTION_FIELDS)
        actual_fields = set(record.keys())

        missing_fields = expected_fields - actual_fields
        unexpected_fields = actual_fields - expected_fields

        if missing_fields:
            raise ValueError(
                "Credential record is missing required fields: "
                f"{sorted(missing_fields)}"
            )

        if unexpected_fields:
            raise ValueError(
                "Credential record contains unexpected fields: "
                f"{sorted(unexpected_fields)}"
            )

        return True

    def validate_records(self, records):
        """Validate a collection of credential records."""

        if records is None:
            raise ValueError(
                "No credential records were provided."
            )

        if not isinstance(records, (list, tuple)):
            raise TypeError(
                "Credential records must be provided as a list or tuple."
            )

        for record in records:
            self.validate_record(record)

        return True

    def create_dataframe(self, records):
        """
        Create a pandas DataFrame using the exact master schema order.

        Sr. No. is generated by the application and is never extracted
        from the document.
        """

        self.validate_records(records)

        rows = []

        for record in records:
            row = {
                field: record.get(field)
                for field in EXTRACTION_FIELDS
            }

            rows.append(row)

        df = pd.DataFrame(
            rows,
            columns=EXTRACTION_FIELDS,
        )

        # Sr. No. is generated by the application.
        df.insert(
            0,
            "Sr. No.",
            range(1, len(df) + 1),
        )

        # Final defensive schema check.
        if list(df.columns) != MASTER_SCHEMA:
            raise ValueError(
                "Generated Excel dataframe does not match "
                "the locked master schema."
            )

        return df
